version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg15
    container_name: mas_pgvector
    environment:
      POSTGRES_USER: mas_user
      POSTGRES_PASSWORD: mas_pass
      POSTGRES_DB: mas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mas_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://mas_user:mas_pass@db:5432/mas_db
    command: uvicorn app.server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
