apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas
  template:
    metadata:
      labels:
        app: mas
    spec:
      containers:
        - name: mas
          image: mas-finance:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mas-service
spec:
  selector:
    app: mas
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
